### ISSUE TITLE
Bug: can't find './src/static/template.html'

### ISSUE THREAD

**Issue by qin-nz** [hua1995116/linec#4]
使用 npm 安装后，使用 `linec -o`，报错

```
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open './src/static/template.html'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at outputHtml (C:\Users\dy\AppData\Roaming\npm\node_modules\linec\lib\linec.js:348:23)
    at linec (C:\Users\dy\AppData\Roaming\npm\node_modules\linec\lib\linec.js:366:18)
    at Object.<anonymous> (C:\Users\dy\AppData\Roaming\npm\node_modules\linec\lib\index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './src/static/template.html'
}
```

**Comment by hua1995116** [comment]
修复，升级至 1.3.8

**Comment by qin-nz** [comment]
确认
